---

- hosts: all
  become: true
  tasks:

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.yaml
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
        