---

- hosts: all #targets all hosts
  become: true #sudo
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package #what the playbook does
    apt:
      name: apache2
      state: latest
      
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest      
