---

- hosts: all #targets all hosts
  become: true #sudo
  tasks:

  - name: install apache2 and php  package #what the playbook does
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Parrot OS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html #destination on target server
      owner: root
      group: root
      mode: 0644

      
  
