---

- hosts: all #targets all hosts
  become: true #sudo
  tasks:

  - name: install apache2 and php  package #what the playbook does
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Parrot OS"
      
  
