---

- hosts: all #targets all hosts
  become: true ##sudo
  tasks:

  - name: remove apache2 and php  package #what the playbook does
    apt:
      name: 
        -apache2
        -libapache2-mod-php
      state: absent 
      update_cache: yes
      
